@startuml Petstore API
(AO_APIProperty) as AO_APIProperty

AO_APIProperty -- "1..1" (Type) : hasType
(Type) <-- (TypeOfInt)
(TypeOfInt) -- (xs:Integer): 数値を持つ
(Type) <-- (TypeOfStr)
(TypeOfStr) -- (xs:String) : 文字列を持つ

(AO_ID) as AO_ID

AO_APIProperty <-- AO_ID : SubClassOf

(AO_DB_ID) --> AO_ID :SubClassOf

(AO_DB_ID) -- (xs:long)

(AO_Name) as AO_Name

AO_APIProperty <-- AO_Name : SubClassOf

(AO_Category) as AO_Category
AO_APIProperty <-- AO_Category : SubClassOf

(AO_URL) as AO_URL
AO_APIProperty <-- AO_URL : SubClassOf

(AO_Tag) as AO_Tag
AO_APIProperty <-- AO_Tag : SubClassOf

(AO_Status) as AO_Status
AO_APIProperty <-- AO_Status : SubClassOf

(AO_StatusName) as AO_StatusName
AO_APIProperty <-- AO_StatusName : SubClassOf

(AO_StatusNumber) as AO_StatusNumber
AO_APIProperty <-- AO_StatusNumber : SubClassOf

(AO_EmailAddress) as AO_EmailAddress
AO_APIProperty <-- AO_EmailAddress : SubClassOf

(AO_Password) as AO_Password
AO_APIProperty <-- AO_Password : SubClassOf

(AO_PhoneNumber) as AO_PhoneNumber
AO_APIProperty <-- AO_PhoneNumber : SubClassOf

(AO_StateNumber) as AO_StateNumber
AO_APIProperty <-- AO_StateNumber : SubClassOf

(AO_Quantity) as AO_Quantity
AO_APIProperty <-- AO_Quantity : SubClassOf

(AO_Choices) as AO_Choices
AO_APIProperty <-- AO_Choices : SubClassOf

(AO_DateTime) as AO_DateTime
AO_APIProperty <-- AO_DateTime : SubClassOf

(AO_Street) as AO_Street
AO_APIProperty <-- AO_Street : SubClassOf

(AO_City) as AO_City
AO_APIProperty <-- AO_City : SubClassOf

(AO_State) as AO_State
AO_APIProperty <-- AO_State : SubClassOf

(AO_ZipCode) as AO_ZipCode
AO_APIProperty <-- AO_ZipCode : SubClassOf

(AO_HttpStatusCode) as AO_HttpStatusCode
AO_APIProperty <-- AO_HttpStatusCode : SubClassOf

(AO_responseType) as AO_responseType
AO_APIProperty <-- AO_responseType : SubClassOf

(AO_Message) as AO_Message
AO_APIProperty <-- AO_Message : SubClassOf

(AO_Type) as AO_Type
AO_APIProperty <-- AO_Type : SubClassOf

(AO_TypeString) as AO_TypeString
AO_Type <-- AO_TypeString : SubClassOf

(AO_TypeInteger) as AO_TypeInteger
AO_Type <-- AO_TypeInteger : SubClassOf

(AO_hasType) as AO_hasType
AO_APIProperty <-- AO_hasType : SubClassOf


rectangle petstore{
    (id) as PetId
    (Pet) -- PetId
    AO_DB_ID -- PetId
    PetId -- TypeOfInt
    PetId -- (1以上) : minimum
}

@enduml