@startuml APPLICATION

class ID{}

Class Name{}

Class Mode{}

note right of Mode
    modeは大体enum？
end note


Class Permission{}

Class 文字列{}
Class 数値{}
Class read{}
Class write{}

Permission --> read
read -- 数値 : 表現
read -- 文字列 : 表現
Permission --> write
write -- 数値 : 表現
write -- 文字列 : 表現

Class User{}
User --> ID
User --> Permission
User --> Name

note as id_note

IDに少なくとも2種類考えられる．
DB上で連番振るようなID
ログインに使用する様なID

end note

Class Authentication{}

Class KnowledgeBasedAuthentication{}
Authentication <|-- KnowledgeBasedAuthentication

Class PossessionBasedAuthentication{}
Authentication <|-- PossessionBasedAuthentication

Class TOTP{}

PossessionBasedAuthentication <|.. TOTP

Class InherentBasedAuthentication{}

Authentication <|-- InherentBasedAuthentication

Class Authorization{}

Class OAuth{}

Authorization <|-- OAuth

Class AccessToken

OAuth-->AccessToken

note as n1
Webシステムに認証/認可は付きもの

パスワードによる認証や
TOTPと組み合わせた多要素認証
OAuthによる認可
end note


Class Billing{}

Class Creditcard{}

Class 現金{}

Class 口座振替{}
Class 銀行振込{}
Class 請求書{}
Class 領収書{}
Class 支払方法{}

Billing -- 支払方法
支払方法 -- Creditcard
支払方法 -- 現金
支払方法 -- 口座振替
支払方法 -- 銀行振込
Billing -- 請求書
Billing -- 領収証

Class Price{}

Price -- Billing
note as billing_note
多くのサービスには何らかの形で支払が発生する，
それはサービスの利用料金にしはらいだったり，ECの注文だったり
支払方法
end note

@enduml