@startuml GitHub API

Class ユーザアカウント{
    login
    name
    id
    email
}

note as todo
GitHubのユーザは色々なURLを持っているからそれ全部列挙していく？
end note

Class ユーザ名

note right of ユーザ名
ユーザ名はログインやアカウント名
end note

Class 表示名
Class ID
Class メールアドレス
Class 名前
note right of 名前
名前も識別子か……
end note

Class general_ID
note right of general_ID
一般的な意味でのID
何かを識別してる
end note

ユーザアカウント -- ユーザ名: ユーザアカウントはユーザ名を持っている
ユーザアカウント -- ID: ユーザアカウントはIDをもっている
ユーザアカウント -- メールアドレス: ユーザアカウントはメールアドレスを持っている

general_ID <|-- ユーザ名:ユーザ名はIDの別形態
名前 <|-- 表示名
general_ID <|-- ID:IDはIDそのものを数字で表す
名前 -- ユーザ名: ユーザ名も広い意味では名前として扱われる


@enduml